M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sat 29 Jul 2023 12:33:07 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-29T12:33:07+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.55Y-4.225
X2.55Y-6.0
X5.6Y-4.225
X5.6Y-6.0
T0
M30
