M48
; DRILL file {KiCad 6.0.7+dfsg-1build1} date Mo 09 Jan 2023 21:05:36 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-09T21:05:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7+dfsg-1build1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X64.77Y-107.315
X64.77Y-152.4
X142.24Y-107.315
X142.24Y-152.4
T0
M30
